### ISSUE TITLE
grunt：command not found

### ISSUE THREAD

**Issue by geoffery009** [forcedotcom/mobile-ui-elements#23]
**i follow this:**
$ git clone https://github.com/ForceDotComLabs/mobile-ui-elements.git
$ cd mobile-ui-elements
$ npm install
$ bower prune (Do this if you are updating an old copy of mobile-ui-elements to remove core-bind dependency.)
$ bower install
To build the project, execute:
**when i execute this:**
$ grunt

**Comment by wmathurin** [comment]
You need to install grunt.
Follow instructions [here](https://stackoverflow.com/questions/15703598/how-to-install-grunt-and-how-to-build-script-with-it).
